### ISSUE TITLE
Installation on Windows fails due to curl requirement

### ISSUE THREAD

**Issue by DCMSstats** [DCMSstats/eesectors#72] opened 2017-02-20 09:25 UTC
Tried to do an install on Windows using standard R 3.1.2 (not RStudio) and installation failed as follows:

Downloading GitHub repo mangothecat/visualTest@master
from URL https://api.github.com/repos/mangothecat/visualTest/zipball/master
Error in utils::packageVersion("curl") : package ‘curl’ not found

Seems curl needs to be in Imports:? Will attempt to fix this...

**Comment by ivyleavedtoadflax** [comment] 2017-02-20 09:46
The R curl package calls a command line tool called (also called curl), which may not be present on all systems. This may be the cause of the problem here, as the windows builds in the automated testing are all passing. http://stackoverflow.com/questions/9507353/how-do-i-install-set-up-and-use-curl-on-a-windows

**Comment by ivyleavedtoadflax** [comment] 2017-03-02 08:21
Fixed in #73.

**Closed as completed by ivyleavedtoadflax** 2017-03-02 08:21 UTC
